### PR TITLE
3 servers

### PR DESCRIPTION
**Pull request by dex4er**

### CODE REVIEW

**Comment by joshpollara** [comment]
@dex4er Hello! Josh from Terrateam here.

I noticed that you're trying to test our service out and it's failing. Couple reasons for this:
- The `tfc-getting-started` repo is specifically designed for Terraform Cloud. It just won't work with Terrateam as is.
- The code required in this version requires a version of the Terraform CLI that wasn't baked into our GitHub Action. I just fixed that.

At this point, you can do two things:
1) Comment `terrateam plan` and watch a run fail because it won't know how to authenticate against Terraform Cloud for the backend
2) Test Terrateam using our `kick-the-tires` template repo https://github.com/terrateamio/kick-the-tires

Onboarding with any platform designed for Terraform can be challenging. Please feel free to hop onto the [Terrateam Slack](https://slack.terrateam.io) for some real-time support. Happy to walk you through everything!

**Comment by dex4er** [comment]
terrateam plan

**Comment by dex4er** [comment]
terrateam plan

**Comment by dex4er** [comment]
terrateam apply

**Comment by dex4er** [comment]
terrateam plan

**Pull request merged**
